'use strict';
Object.defineProperty(exports, '__esModule', {value: true});
const listNode_1 = require('./listNode');
const index_1 = require('./index');
const one = new listNode_1.default(1);
const two = new listNode_1.default(2);
const three = new listNode_1.default(3);
const four = new listNode_1.default(4);
const five = new listNode_1.default(5);
one.next = two;
two.next = three;
three.next = four;
four.next = five;
console.log(one.print());
console.log('\nReversed (k=2):');
const rev = index_1.default(one, 2);
console.log(rev.print());
console.log('\nReversed (k=3):');
const rev3 = index_1.default(one, 3);
console.log(rev3.print());
